"""initial schema

Revision ID: d4f6367271f9
Revises: 
Create Date: 2026-08-18 11:35:56.302326

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd4f6367271f9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_log_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_log_created_at'), ['created_at'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('bank_key', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=16), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('holder_name', sa.String(length=120), nullable=True),
    sa.Column('operator', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'account_number', 'bank_key', name='uq_account_identity')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index('ix_accounts_number', ['account_number'], unique=False)

    op.create_table('excluded_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excluded_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excluded_numbers_value'), ['value'], unique=True)

    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_slug'), ['slug'], unique=True)

    op.create_table('account_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'site_id', name='uq_account_site')
    )
    with op.batch_alter_table('account_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_sites_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_sites_site_id'), ['site_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_type'), ['type'], unique=False)

    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('fetcher', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('accounts_new', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_runs_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_runs_status'), ['status'], unique=False)

    op.create_table('site_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('url_type', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'url', name='uq_site_url')
    )
    with op.batch_alter_table('site_urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_urls_site_id'), ['site_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_sha256'), ['sha256'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('origin', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['collection_runs.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_observations_account_time', ['account_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_site_id'))
        batch_op.drop_index(batch_op.f('ix_observations_run_id'))
        batch_op.drop_index(batch_op.f('ix_observations_observed_at'))
        batch_op.drop_index('ix_observations_account_time')
        batch_op.drop_index(batch_op.f('ix_observations_account_id'))

    op.drop_table('observations')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_sha256'))
        batch_op.drop_index(batch_op.f('ix_evidence_run_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('site_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_urls_site_id'))

    op.drop_table('site_urls')
    with op.batch_alter_table('collection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_runs_status'))
        batch_op.drop_index(batch_op.f('ix_collection_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_collection_runs_site_id'))

    op.drop_table('collection_runs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('account_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_sites_site_id'))
        batch_op.drop_index(batch_op.f('ix_account_sites_account_id'))

    op.drop_table('account_sites')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_slug'))

    op.drop_table('sites')
    with op.batch_alter_table('excluded_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excluded_numbers_value'))

    op.drop_table('excluded_numbers')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_number')
        batch_op.drop_index(batch_op.f('ix_accounts_needs_review'))
        batch_op.drop_index(batch_op.f('ix_accounts_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_active'))
        batch_op.drop_index(batch_op.f('ix_accounts_channel'))

    op.drop_table('accounts')
    with op.batch_alter_table('access_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_access_log_actor'))

    op.drop_table('access_log')
    # ### end Alembic commands ###
